# Generated by Django 4.2.4 on 2023-11-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student", name="address", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="age",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="0",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mail_id",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
