# Generated by Django 4.2.4 on 2023-11-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_rename_college_department"),
    ]

    operations = [
        migrations.RenameModel(old_name="Department", new_name="College",),
        migrations.AlterField(
            model_name="student", name="age", field=models.IntegerField(default=0),
        ),
    ]
